name: Run tests from makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker test
      run: |
        /usr/bin/bash --version
        /bin/bash --version
        make
